server:
  name: ${SERVER_NAME:myserver1}
  url: ${SERVER_URL:myserver1}
  port: ${SERVER_PORT:8081}
  nums-of-node: 4
  server-list:
    - myserver1:myserver1:8101:4
    - myserver2:myserver2:8102:4
    - myserver3:myserver3:8103:4
    - myserver4:myserver4:8104:4
    - myserver5:myserver5:8105:4
    - myserver6:myserver6:8106:4

quorum:
  number-of-replica: 3
  write: 2
  read: 2

gossip:
  threshold:
    temporary: 20
    permanent: 300

hash:
  function: md5 #custom
  consistent: true
  node-nums: 4
spring:
  devtools:
    add-properties: false
  data:
    mongodb:
      database: ${SERVER_NAME:myserver1}


influxdb:
  run: false
  url: http://influxdb:8086
  token: FtiI_iKAHZgL3uVSe8Fn8FWO09d51IUHsE-pBBwEaWsrolqXL8NZITP4NpfJGb4PpwpSsU_X6EwqgEC2waHI3A==
  bucket: kvdb
  org: 0manhour