{
 "title": "Key-Value Database",
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  {
   "title": "Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "[S1]Key",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"key\" and r.server == \"myserver1\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"method\", \"key\", \"value\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n"
      }
     ]
    },
    {
     "title": "[S1]Quorum",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"quorum\" and r.server == \"myserver1\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"method\", \"key\", \"value\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n"
      }
     ]
    },
    {
     "title": "[S4]Key",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"key\" and r.server == \"myserver4\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"method\", \"key\", \"value\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n"
      }
     ]
    },
    {
     "title": "[S4]Quorum",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"quorum\" and r.server == \"myserver4\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"method\", \"key\", \"value\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n"
      }
     ]
    },
    {
     "title": "[S2]Key",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"key\" and r.server == \"myserver2\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"method\", \"key\", \"value\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n"
      }
     ]
    },
    {
     "title": "[S2]Quorum",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"quorum\" and r.server == \"myserver2\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"method\", \"key\", \"value\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n"
      }
     ]
    },
    {
     "title": "[S5]Key",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"key\" and r.server == \"myserver5\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"method\", \"key\", \"value\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n"
      }
     ]
    },
    {
     "title": "[S5]Quorum",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"quorum\" and r.server == \"myserver5\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"method\", \"key\", \"value\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n"
      }
     ]
    },
    {
     "title": "[S3]Key",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"key\" and r.server == \"myserver3\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"method\", \"key\", \"value\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n"
      }
     ]
    },
    {
     "title": "[S3]Quorum",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"quorum\" and r.server == \"myserver3\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"method\", \"key\", \"value\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n"
      }
     ]
    },
    {
     "title": "[S6]Key",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"key\" and r.server == \"myserver6\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"method\", \"key\", \"value\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n"
      }
     ]
    },
    {
     "title": "[S6]Quorum",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"quorum\" and r.server == \"myserver6\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"method\", \"key\", \"value\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "MerkleTree-Hash",
     "type": "table",
     "gridPos": { "h": 10, "w": 15, "x": 0, "y": 2 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"merkle\")\n  |> group(columns: [\"partition\", \"server\"])  // partition과 server로 그룹화\n  |> last()  // 각 그룹에서 가장 최신의 값을 선택\n  |> group()\n  |> keep(columns: [\"partition\", \"_value\", \"server\"])  // 필요한 열만 유지\n  |> pivot(rowKey: [\"partition\"], columnKey: [\"server\"], valueColumn: \"_value\")  // 데이터를 피벗하여 행과 열을 변환\n\n"
      }
     ]
    },
    {
     "title": "[S1]Handoff",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"handoff\" and r.server == \"myserver1\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"from\", \"key\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"key\")\n  |> group(columns: [\"from\"])\n  |> keep(columns: [\"_time\", \"from\", \"key\", \"command\"])\n  |> filter(fn: (r) => r.command == \"KEEP\")\n  |> count(column: \"key\")\n  |> group()"
      }
     ]
    },
    {
     "title": "[S2]Handoff",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 12 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"handoff\" and r.server == \"myserver2\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"from\", \"key\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"key\")\n  |> group(columns: [\"from\"])\n  |> keep(columns: [\"_time\", \"from\", \"key\", \"command\"])\n  |> filter(fn: (r) => r.command == \"KEEP\")\n  |> count(column: \"key\")\n  |> group()"
      }
     ]
    },
    {
     "title": "[S3]Handoff",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 12 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"handoff\" and r.server == \"myserver3\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"from\", \"key\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"key\")\n  |> group(columns: [\"from\"])\n  |> keep(columns: [\"_time\", \"from\", \"key\", \"command\"])\n  |> filter(fn: (r) => r.command == \"KEEP\")\n  |> count(column: \"key\")\n  |> group()"
      }
     ]
    },
    {
     "title": "[S4]Handoff",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 18 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"handoff\" and r.server == \"myserver4\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"from\", \"key\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"key\")\n  |> group(columns: [\"from\"])\n  |> keep(columns: [\"_time\", \"from\", \"key\", \"command\"])\n  |> filter(fn: (r) => r.command == \"KEEP\")\n  |> count(column: \"key\")\n  |> group()"
      }
     ]
    },
    {
     "title": "[S5]Handoff",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 18 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"handoff\" and r.server == \"myserver5\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"from\", \"key\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"key\")\n  |> group(columns: [\"from\"])\n  |> keep(columns: [\"_time\", \"from\", \"key\", \"command\"])\n  |> filter(fn: (r) => r.command == \"KEEP\")\n  |> count(column: \"key\")\n  |> group()"
      }
     ]
    },
    {
     "title": "[S6]Handoff",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 18 },
     "targets": [
      {
       "query": "from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"handoff\" and r.server == \"myserver6\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"from\", \"key\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"key\")\n  |> group(columns: [\"from\"])\n  |> keep(columns: [\"_time\", \"from\", \"key\", \"command\"])\n  |> filter(fn: (r) => r.command == \"KEEP\")\n  |> count(column: \"key\")\n  |> group()"
      }
     ]
    },
    {
     "title": "[S1]Gossip",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
     "targets": [
      {
       "query": "heartbeat_data = from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gossip\" and r.from == \"myserver1\" and r._field == \"heartbeat\")\n  |> group(columns: [\"server\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"server\", \"_value\"])\n  |> rename(columns: {_value: \"heartbeat\"})\n\nstatus_data = from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gossip\" and r.from == \"myserver1\" and r._field == \"status\")\n  |> group(columns: [\"server\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"server\", \"_value\"])\n  |> rename(columns: {_value: \"status\"})\n\njoin(\n  tables: {heartbeat: heartbeat_data, status: status_data},\n  on: [\"server\", \"_time\"]\n)\n|> keep(columns: [\"server\", \"heartbeat\", \"status\", \"_time\"])\n|>group()\n"
      }
     ]
    },
    {
     "title": "[S2]Gossip",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 24 },
     "targets": [
      {
       "query": "heartbeat_data = from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gossip\" and r.from == \"myserver2\" and r._field == \"heartbeat\")\n  |> group(columns: [\"server\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"server\", \"_value\"])\n  |> rename(columns: {_value: \"heartbeat\"})\n\nstatus_data = from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gossip\" and r.from == \"myserver2\" and r._field == \"status\")\n  |> group(columns: [\"server\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"server\", \"_value\"])\n  |> rename(columns: {_value: \"status\"})\n\njoin(\n  tables: {heartbeat: heartbeat_data, status: status_data},\n  on: [\"server\", \"_time\"]\n)\n|> keep(columns: [\"server\", \"heartbeat\", \"status\", \"_time\"])\n|>group()\n"
      }
     ]
    },
    {
     "title": "[S3]Gossip",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 24 },
     "targets": [
      {
       "query": "heartbeat_data = from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gossip\" and r.from == \"myserver3\" and r._field == \"heartbeat\")\n  |> group(columns: [\"server\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"server\", \"_value\"])\n  |> rename(columns: {_value: \"heartbeat\"})\n\nstatus_data = from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gossip\" and r.from == \"myserver3\" and r._field == \"status\")\n  |> group(columns: [\"server\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"server\", \"_value\"])\n  |> rename(columns: {_value: \"status\"})\n\njoin(\n  tables: {heartbeat: heartbeat_data, status: status_data},\n  on: [\"server\", \"_time\"]\n)\n|> keep(columns: [\"server\", \"heartbeat\", \"status\", \"_time\"])\n|>group()\n"
      }
     ]
    },
    {
     "title": "[S4]Gossip",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 32 },
     "targets": [
      {
       "query": "heartbeat_data = from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gossip\" and r.from == \"myserver4\" and r._field == \"heartbeat\")\n  |> group(columns: [\"server\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"server\", \"_value\"])\n  |> rename(columns: {_value: \"heartbeat\"})\n\nstatus_data = from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gossip\" and r.from == \"myserver4\" and r._field == \"status\")\n  |> group(columns: [\"server\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"server\", \"_value\"])\n  |> rename(columns: {_value: \"status\"})\n\njoin(\n  tables: {heartbeat: heartbeat_data, status: status_data},\n  on: [\"server\", \"_time\"]\n)\n|> keep(columns: [\"server\", \"heartbeat\", \"status\", \"_time\"])\n|>group()\n"
      }
     ]
    },
    {
     "title": "[S5]Gossip",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 32 },
     "targets": [
      {
       "query": "heartbeat_data = from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gossip\" and r.from == \"myserver5\" and r._field == \"heartbeat\")\n  |> group(columns: [\"server\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"server\", \"_value\"])\n  |> rename(columns: {_value: \"heartbeat\"})\n\nstatus_data = from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gossip\" and r.from == \"myserver5\" and r._field == \"status\")\n  |> group(columns: [\"server\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"server\", \"_value\"])\n  |> rename(columns: {_value: \"status\"})\n\njoin(\n  tables: {heartbeat: heartbeat_data, status: status_data},\n  on: [\"server\", \"_time\"]\n)\n|> keep(columns: [\"server\", \"heartbeat\", \"status\", \"_time\"])\n|>group()\n"
      }
     ]
    },
    {
     "title": "[S6]Gossip",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 32 },
     "targets": [
      {
       "query": "heartbeat_data = from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gossip\" and r.from == \"myserver6\" and r._field == \"heartbeat\")\n  |> group(columns: [\"server\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"server\", \"_value\"])\n  |> rename(columns: {_value: \"heartbeat\"})\n\nstatus_data = from(bucket: \"kvdb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gossip\" and r.from == \"myserver6\" and r._field == \"status\")\n  |> group(columns: [\"server\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"server\", \"_value\"])\n  |> rename(columns: {_value: \"status\"})\n\njoin(\n  tables: {heartbeat: heartbeat_data, status: status_data},\n  on: [\"server\", \"_time\"]\n)\n|> keep(columns: [\"server\", \"heartbeat\", \"status\", \"_time\"])\n|>group()\n"
      }
     ]
    }
   ]
  },
  {
   "title": "MerkleDetail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "[S1]Merkle",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 3, "y": 3 },
     "targets": [
      {
       "query": "  from(bucket: \"kvdb\")\n  |> range(start: -24h)  // 데이터의 시간 범위를 설정 (예: 지난 1시간)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"merkle\" and r[\"server\"] == \"myserver1\")\n  |> group(columns: [\"partition\"])\n  |> last()\n  |> group()\n  |> keep(columns: [ \"_value\", \"partition\", \"_time\"])  // 필요한 열만 유지\n\n"
      }
     ]
    },
    {
     "title": "[S2]Merkle",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 9, "y": 3 },
     "targets": [
      {
       "query": "  from(bucket: \"kvdb\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"merkle\" and r[\"server\"] == \"myserver2\")\n  |> group(columns: [\"partition\"])\n  |> last()\n  |> group()\n  |> keep(columns: [ \"_value\", \"partition\", \"_time\"])  // 필요한 열만 유지\n\n"
      }
     ]
    },
    {
     "title": "[S3]Merkle",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 15, "y": 3 },
     "targets": [
      {
       "query": "  from(bucket: \"kvdb\")\n  |> range(start: -24h)  // 데이터의 시간 범위를 설정 (예: 지난 1시간)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"merkle\" and r[\"server\"] == \"myserver3\")\n  |> group(columns: [\"partition\"])\n  |> last()\n  |> group()\n  |> keep(columns: [ \"_value\", \"partition\", \"_time\"])  // 필요한 열만 유지\n\n"
      }
     ]
    },
    {
     "title": "[S4]Merkle",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 3, "y": 9 },
     "targets": [
      {
       "query": "  from(bucket: \"kvdb\")\n  |> range(start: -24h)  // 데이터의 시간 범위를 설정 (예: 지난 1시간)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"merkle\" and r[\"server\"] == \"myserver4\")\n  |> group(columns: [\"partition\"])\n  |> last()\n  |> group()\n  |> keep(columns: [ \"_value\", \"partition\", \"_time\"])  // 필요한 열만 유지\n\n"
      }
     ]
    },
    {
     "title": "[S5]Merkle",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 9, "y": 9 },
     "targets": [
      {
       "query": "  from(bucket: \"kvdb\")\n  |> range(start: -24h)  // 데이터의 시간 범위를 설정 (예: 지난 1시간)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"merkle\" and r[\"server\"] == \"myserver5\")\n  |> group(columns: [\"partition\"])\n  |> last()\n  |> group()\n  |> keep(columns: [ \"_value\", \"partition\", \"_time\"])  // 필요한 열만 유지\n\n"
      }
     ]
    },
    {
     "title": "[S6]Merkle",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 15, "y": 9 },
     "targets": [
      {
       "query": "  from(bucket: \"kvdb\")\n  |> range(start: -24h)  // 데이터의 시간 범위를 설정 (예: 지난 1시간)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"merkle\" and r[\"server\"] == \"myserver6\")\n  |> group(columns: [\"partition\"])\n  |> last()\n  |> group()\n  |> keep(columns: [ \"_value\", \"partition\", \"_time\"])  // 필요한 열만 유지\n\n"
      }
     ]
    }
   ]
  }
 ]
}